#!/bin/bash

#set -vx

if [ $# = 0 ]
then
   echo " "
   echo "Usage: gat-file-operation [OPTIONS] <operation> <source> <dest>"
   echo " "
   echo "   OPTIONS:"
   echo " "
   echo "   -Adaptor   [STRING]   force the use of a specific file adaptor"
   echo " "
   echo "   <operation>: RemoteCopy, RemoteMove or DeleteFile"
   echo "   <source>:    source file"
   echo "   <dest>:      destination file; not used at <operation> DeleteFile"
   echo " "
   exit 1
fi

SDIR=`dirname $0`

#java -jar -classpath $SDIR/../dist/lib/commons-logging.jar:$SDIR/../dist/lib/colobus.jar:$SDIR/../lib/log4j-1.2.13.jar:$SDIR/../lib/ibis-util-1.4.jar:$SDIR/../lib/commons-cli-1.0.jar -Dgat.adaptor.path=$GAT_LOCATION/adaptors/lib -Dlog4j.configuration=file:$SDIR/../log4j.properties $SDIR/../dist/GATFileOps.jar $@

java -jar -Dgat.debug -Dgat.adaptor.path=$GAT_LOCATION/lib/adaptors -Dlog4j.configuration=file: $GAT_LOCATION/astrogrid-packages/GATFileOps/log4j.properties $GAT_LOCATION/astrogrid-packages/GATFileOps/dist/GATFileOps.jar $@

exit

