#!/bin/bash

#set -vx

#SDIR=`dirname $0`


#java -jar -classpath $GAT_TEST/dist/lib/ -Dgat.debug -Dgat.adaptor.path=$GAT_LOCATION/adaptors/lib $SDIR/../dist/GATJobRun.jar $@
#java -jar -classpath $GAT_TEST/dist/lib/:$GAT_LOCATION/adaptors/external/drmaa.jar -Dgat.debug -Dorg.ggf.drmaa.SessionFactory=com.sun.grid.drmaa.SessionFactoryImpl -Dgat.adaptor.path=$GAT_LOCATION/adaptors/lib $SDIR/../dist/GATJobRun.jar $@
#java -jar -Dorg.ggf.drmaa.SessionFactory=com.sun.grid.drmaa.SessionFactoryImpl -Dgat.adaptor.path=$GAT_LOCATION/lib/adaptors $SDIR/../dist/GATJobRun.jar $@
java -jar -Dorg.ggf.drmaa.SessionFactory=com.sun.grid.drmaa.SessionFactoryImpl -Dgat.adaptor.path=$GAT_LOCATION/lib/adaptors -Dlog4j.configuration=file:$GAT_LOCATION/log4j.properties $GAT_LOCATION/astrogrid-packages/GATJobRun/dist/GATJobRun.jar $@
#java -jar -Dlog4j.configuration=file:/home/alibeck/programme/javagat-2.0-trunk-globus-fixed/astrogrid-packages/Tutorial/JobProgs/log4j.properties -Dorg.ggf.drmaa.SessionFactory=com.sun.grid.drmaa.SessionFactoryImpl -Dgat.adaptor.path=$GAT_LOCATION/lib/adaptors $GAT_LOCATION/astrogrid-packages/GATJobRun/dist/GATJobRun.jar $@
