/*
 * Created on Oct 24, 2006
 */
package org.gridlab.gat.resources.cpi.globus;

public class GramError {
    private static String[] errorStrings = new String[] {
        "PARAMETER_NOT_SUPPORTED",
        "INALID_REQUEST",
        "NO_RESOURCES",
        "BAD_DIRECTORY",
        "EXECUTABLE_NOT_FOUND",
        "INSUFFICIENT_FUNDS",
        "ERROR_AUTHORIZATION",
        "USER_CANCELLED",
        "SYSTEM_CANCELLED",
        "PROTOCOL_FAILED",
        "STDIN_NOT_FOUND",
        "CONNECTION_FAILED",
        "INVALID_MAXTIME",
        "INVALID_COUNT",
        "NULL_SPECIFICATION_TREE",
        "JM_FAILED_ALLOW_ATTACH",
        "JOB_EXECUTION_FAILED",
        "INVALID_PARADYN",
        "INVALID_JOBTYPE",
        "INVALID_MYJOB",
        "BAD_SCRIPT_ARG_FILE",
        "ARG_FILE_CREATION_FAILED",
        "INVALID_JOBSTATUS",
        "INVALID_SCRIPT_REPLY",
        "INVALID_SCRIPT_STATUS",
        "MPI_NOT_SUPPORTED",
        "UNIMPLEMENTED",
        "TEMP_SCRIPT_FILE_FAILED",
        "USER_PROXY_NOT_FOUND",
        "PROXY_FILE_OPEN_FAILED",
        "JOB_CANCEL_FAILED",
        "MALLOC_FAILED",
        "DUCT_INIT_FAILED",
        "DUCT_LSP_FAILED",
        "INVALID_HOST_COUNT",
        "UNSUPPORTED_PARAMETER",
        "INVALID_QUEUE",
        "INVALID_PROJECT",
        "RSL_EVALUATION_FAILED",
        "BAD_RSL_ENVIRONMENT",
        "DRYRUN",
        "ZERO_LENGTH_RSL",
        "ERROR_STAGING_EXECUTABLE",
        "ERROR_STAGING_STDIN",
        "INVALID_JOB_MANAGER_TYPE",
        "BAD_ARGUMENTS",
        "GATEKEEPER_MISCONFIGURED",
        "BAD_RSL",
        "VERSION_MISMATCH",
        "RSL_ARGUMENTS",
        "RSL_COUNT",
        "RSL_DIRECTORY",
        "RSL_DRYRUN",
        "RSL_ENVIRONMENT",
        "RSL_EXECUTABLE",
        "RSL_HOST_COUNT",
        "RSL_JOBTYPE",
        "RSL_MAXTIME",
        "RSL_MYJOB",
        "ERROR_RSL_PARADYN",
        "ERROR_RSL_PROJECT",
        "ERROR_RSL_QUEUE",
        "ERROR_RSL_STDERR",
        "ERROR_RSL_STDIN",
        "ERROR_RSL_STDOUT",
        "ERROR_OPENING_JOBMANAGER_SCRIPT",
        "ERROR_CREATING_PIPE",
        "ERROR_FCNTL_FAILED",
        "ERROR_STDOUT_FILENAME_FAILED",
        "ERROR_STDERR_FILENAME_FAILED",
        "ERROR_FORKING_EXECUTABLE",
        "EXECUTABLE_PERMISSIONS",
        "ERROR_OPENING_STDOUT",
        "ERROR_OPENING_STDERR",
        "ERROR_OPENING_CACHE_USER_PROXY",
        "ERROR_OPENING_CACHE",
        "ERROR_INSERTING_CLIENT_CONTACT",
        "CLIENT_CONTACT_NOT_FOUND",
        "ERROR_CONTACTING_JOB_MANAGER",
        "INVALID_JOB_CONTACT",
        "EXECUTABLE_UNDEFINED",
        "INVALID_MIN_MEMORY",
        "INVALID_MAX_MEMORY",
        "HTTP_UNFRAME_FAILED",
        "HTTP_UNPACK_FAILED",
        "INVALID_JOB_QUERY",
        "ERROR_SERVICE_NOT_FOUND",
        "JOB_QUERY_DENIAL",
        "CALLBACK_NOT_FOUND",
        "BAD_GATEKEEPER_CONTACT",
        "INVALID_MAX_WALL_TIME",
        "INVALID_MAX_CPU_TIME",
        "ERROR_SIGNALING_JOB",
        "UNKNOWN_SIGNAL_TYPE",
        "WAITING_FOR_COMMIT",
        "COMMIT_TIMED_OUT",
    };
    
    public static String getGramErrorString(int errorCode) {
        if(errorCode <0 || errorCode >= errorStrings.length) {
            return "UNKNOWN_ERROR";
        }
        
        return errorCode + ": " + errorStrings[errorCode];
    }
}
